name: ff_moneyblaster
description: "A new Flutter project."

publish_to: 'none' 

version: 2.0.0+2

environment:
  sdk: '>=3.2.6 <4.0.0'


dependencies:
  auto_route: ^8.0.3
  bottom_sheet: ^4.0.4
  carousel_slider: ^4.2.1
  clipboard: ^0.1.3
  cloud_firestore: ^4.17.0
  cupertino_icons: ^1.0.2
  firebase_auth: ^4.17.8
  firebase_core: ^2.30.1
  firebase_messaging: ^14.9.1
  flutter:
    sdk: flutter
  flutter_local_notifications: ^17.1.1
  flutter_riverpod: ^2.5.1
  flutter_svg: ^2.0.9
  fluttertoast: ^8.2.5
  freezed: ^2.5.2
  freezed_annotation: ^2.4.1
  gradient_borders: ^1.0.0
  image_picker: ^1.1.1
  intl: ^0.19.0
  lottie: ^3.0.0
  provider: ^6.1.2
  pull_to_refresh: ^2.0.0
  rive: ^0.13.1
  riverpod: ^2.5.1
  shared_preferences: ^2.2.3
  sizer: ^2.0.15
  url_launcher: ^6.2.6
  video_player: ^2.8.3
  permission_handler: ^11.3.1

  
dev_dependencies:
  auto_route_generator: ^8.0.0
  build_runner: null
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.8.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/launcher.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/animations/
    - assets/images/
    - assets/icons/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Apex
      fonts:
        - asset: fonts/Apex-Regular.ttf
          weight: 400
        - asset: fonts/Apex-Medium.ttf
          weight: 600
        - asset: fonts/Apex-SemiBold.ttf
          weight: 700
        - asset: fonts/Apex-Bold.ttf
          weight: 900
    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat-Regular.ttf
          weight: 400
        - asset: fonts/Montserrat-Medium.ttf
          weight: 600
        - asset: fonts/Montserrat-SemiBold.ttf
          weight: 700
        - asset: fonts/Montserrat-Bold.ttf
          weight: 900
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
